CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE DEPARTMENTS(DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(100));
CREATE TABLE LOCATION(LOCATION_ID INT PRIMARY KEY,
LOCATION VARCHAR(30));
CREATE TABLE EMPLOYEES(EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50),
GENDER ENUM("M","F"),AGE INT,
HIRE_DATE DATE,DESIGNATION VARCHAR(100),
DEPARTMENT_ID INT,LOCATION_ID INT,
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),SALARY DECIMAL(10,2));

ALTER TABLE EMPLOYEES ADD COLUMN EMAIL VARCHAR(50);
ALTER TABLE EMPLOYEES MODIFY DESIGNATION VARCHAR(500);
ALTER TABLE EMPLOYEES DROP COLUMN AGE;
ALTER TABLE EMPLOYEES RENAME COLUMN HIRE_DATE TO DATE_OF_JOINING;
RENAME TABLE DEPARTMENTS TO DEPARTMENTS_INFO;
RENAME TABLE LOCATION TO LOCATIONS;
TRUNCATE TABLE EMPLOYEES;
DROP TABLE EMPLOYEES;
DROP DATABASE EMPLOYEE;

CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE DEPARTMENTS(DEPARTMENT_ID INT PRIMARY KEY UNIQUE,
DEPARTMENT_NAME VARCHAR(100) NOT NULL UNIQUE);

CREATE TABLE LOCATION(LOCATION_ID INT AUTO_INCREMENT PRIMARY KEY,
LOCATION VARCHAR(30) UNIQUE NOT NULL);

CREATE TABLE EMPLOYEES(EMPLOYEE_ID INT  UNIQUE PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50) NOT NULL,
GENDER ENUM("M","F"),
AGE INT CHECK (AGE>=18),
HIRE_DATE DATE DEFAULT(CURRENT_DATE),
DESIGNATION VARCHAR(100),DEPARTMENT_ID INT,
LOCATION_ID INT,
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),
SALARY DECIMAL(10,2));
